title: Barber Shop Village
theme: jekyll-theme-cayman
description: Portfólio destinado a mostrar informações sobre o projeto do site "Barber Shop Village"
a ser desenvolvido durante o curso de Aplicação de Engenharia de Software da UNISUL.
show_downloads: true
